import argparse
import errno
import logging

from .. import __version__, notifications
from ..logging_config import configure_logging
from . import doctor, init, listen, monitor, service, status, validate

logger = logging.getLogger(__name__)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog='macropad', description='Turn every keyboard into a Macropad'
    )
    parser.add_argument('--version', action='version', version=f'%(prog)s {__version__}')
    verbosity = parser.add_mutually_exclusive_group()
    verbosity.add_argument(
        '--verbose',
        action='store_true',
        help='Show lifecycle and action summary logs.',
    )
    verbosity.add_argument(
        '--debug',
        action='store_true',
        help='Show detailed input, layer, and action logs.',
    )
    parser.add_argument(
        '--action-debug',
        action='store_true',
        help='Enable debug logs and inherit action stdout/stderr.',
    )
    parser.add_argument(
        '--no-notifications',
        action='store_true',
        help='Disable optional desktop notifications.',
    )
    subparsers = parser.add_subparsers(title='Subcommands', dest='subcommand', required=True)

    validate_subparser = subparsers.add_parser(
        'validate',
        help='Validate profiles without opening input devices',
        description='Load, validate, and merge profiles without opening input devices.',
        epilog='See README.md#profile-format for the complete profile format.',
    )
    validate_subparser.add_argument(
        'profile_paths', nargs='*', help='Paths to macropad profile files.'
    )
    validate_subparser.add_argument(
        '--directory',
        '-d',
        action='append',
        dest='profile_directories',
        help='Directory containing profile files (.yml). Can be specified multiple times.',
    )

    subparsers.add_parser(
        'doctor',
        help='Check input permissions and runtime environment',
    )

    subparsers.add_parser(
        'status',
        help='Show live keyboard worker and device state',
    )

    init_subparser = subparsers.add_parser(
        'init',
        help='Create a first profile through guided device and key detection',
    )
    init_subparser.add_argument(
        '--timeout',
        type=init.timeout_seconds,
        default=60.0,
        help='Seconds to wait for each device or key capture (default: 60).',
    )

    monitor_subparser = subparsers.add_parser(
        'monitor',
        help='List input devices or stream key events without grabbing',
    )
    monitor_subparser.add_argument(
        'device',
        nargs='?',
        help='Exact input device name to monitor. Omit to list readable devices.',
    )

    listen_subparser = subparsers.add_parser('listen', help='Intercept profile device')
    listen_subparser.add_argument(
        'profile_paths', nargs='*', help='Paths to your macropad profiles.'
    )
    listen_subparser.add_argument(
        '--directory',
        '-d',
        action='append',
        dest='profile_directories',
        help='Directory containing profile files (.yml). Can be specified multiple times.',
    )
    listen_subparser.add_argument(
        '--watch',
        action='store_true',
        help='Watch profile directories for changes and automatically reload.',
    )

    service_subparser = subparsers.add_parser(
        'service',
        help='Manage the systemd user service',
    )
    service_subparsers = service_subparser.add_subparsers(
        title='Service actions',
        dest='service_action',
        required=True,
    )
    service_action_help = {
        'install': 'Install, enable, and start the service',
        'uninstall': 'Stop, disable, and remove the service',
        'enable': 'Enable the service at login',
        'disable': 'Disable the service at login',
        'start': 'Start the service',
        'stop': 'Stop the service',
        'restart': 'Restart the service',
        'status': 'Show service status',
        'logs': 'Follow service logs',
    }
    for action in service.SERVICE_ACTIONS:
        action_parser = service_subparsers.add_parser(action, help=service_action_help[action])
        if action == 'install':
            action_parser.add_argument(
                '--force',
                action='store_true',
                help='Replace an existing unit not generated by Macropad.',
            )

    return parser.parse_args()


def main() -> int:
    args = parse_args()
    configure_logging(
        verbose=getattr(args, 'verbose', False),
        debug=getattr(args, 'debug', False) or getattr(args, 'action_debug', False),
    )
    notifications_enabled = not getattr(args, 'no_notifications', False)
    notifications.configure(notifications_enabled)
    try:
        if args.subcommand == 'doctor':
            return doctor.run()
        if args.subcommand == 'init':
            return init.run(args)
        if args.subcommand == 'status':
            return status.run()
        if args.subcommand == 'monitor':
            return monitor.run(args)
        if args.subcommand == 'service':
            return service.run(
                args.service_action,
                force=getattr(args, 'force', False),
                notifications_enabled=notifications_enabled,
            )
        if args.subcommand == 'listen':
            return listen.run(args)
        return validate.run(args)
    except KeyboardInterrupt:
        logger.info('keyboard interrupt received; exiting')
    except OSError as error:
        if error.errno == errno.ENODEV:
            logger.warning('input device lost; exiting', extra={'error': str(error)})
        else:
            logger.exception('operating system error; exiting', extra={'error': str(error)})
            return 1

    return 0
