import shlex
import subprocess
from dataclasses import dataclass
from pathlib import Path

from .. import service_unit

SERVICE_NAME = service_unit.SERVICE_NAME
SYSTEMCTL_ACTIONS = (
    'enable',
    'disable',
    'start',
    'stop',
    'restart',
    'status',
)
SERVICE_ACTIONS = (
    'install',
    'uninstall',
    *SYSTEMCTL_ACTIONS,
    'logs',
)


@dataclass(frozen=True)
class ServiceInfo:
    fragment_path: str | None
    active: bool
    error: str | None = None
    action_path: str | None = None


def get_info() -> ServiceInfo:
    command = [
        'systemctl',
        '--user',
        'show',
        SERVICE_NAME,
        '--property=FragmentPath',
        '--property=ActiveState',
        '--property=Environment',
    ]
    try:
        completed = subprocess.run(
            command,
            check=False,
            capture_output=True,
            text=True,
            timeout=5,
        )
    except OSError as error:
        return ServiceInfo(None, False, f'systemctl is unavailable: {error}')
    except subprocess.TimeoutExpired:
        return ServiceInfo(
            None,
            False,
            'The systemd user manager did not respond within five seconds.',
        )

    properties = {}
    for line in completed.stdout.splitlines():
        name, separator, value = line.partition('=')
        if separator:
            properties[name] = value
    fragment_path = properties.get('FragmentPath')
    if completed.returncode == 0 and fragment_path:
        try:
            environment = shlex.split(properties.get('Environment', ''))
        except ValueError:
            environment = []
        action_path = next(
            (
                assignment.removeprefix('PATH=')
                for assignment in environment
                if assignment.startswith('PATH=')
            ),
            None,
        )
        return ServiceInfo(
            fragment_path,
            properties.get('ActiveState') == 'active',
            action_path=action_path,
        )
    return ServiceInfo(
        None,
        False,
        'The macropad systemd user service is not installed or unavailable.',
    )


def _run_systemctl(*arguments: str) -> int:
    return subprocess.run(['systemctl', '--user', *arguments], check=False).returncode


def install(force: bool = False, notifications_enabled: bool = True) -> int:
    try:
        executable = service_unit.resolve_executable()
        unit_path = service_unit.resolve_unit_path()
        service_info = get_info()
        if service_info.fragment_path:
            service_unit.validate_unit_ownership(Path(service_info.fragment_path), force)
        service_unit.install_unit(
            unit_path,
            service_unit.render_unit(executable, notifications_enabled),
            force=force,
        )
    except (OSError, ValueError, RuntimeError) as error:
        print(f'Could not install service: {error}')
        return 1

    if _run_systemctl('daemon-reload'):
        return 1
    if _run_systemctl('enable', SERVICE_NAME):
        return 1
    result = _run_systemctl('start', SERVICE_NAME)
    if result == 0:
        print(f'Installed, enabled, and started {unit_path}')
    return result


def uninstall() -> int:
    try:
        unit_path = service_unit.resolve_unit_path()
        if not unit_path.exists():
            print('Macropad service is not installed.')
            return 0
        content = unit_path.read_text(encoding='utf-8')
        if not service_unit.is_generated_unit(content):
            raise service_unit.UnitOwnershipError(
                f'{unit_path} was not generated by Macropad; refusing to remove it'
            )
    except (OSError, RuntimeError) as error:
        print(f'Could not uninstall service: {error}')
        return 1

    if _run_systemctl('stop', SERVICE_NAME):
        return 1
    if _run_systemctl('disable', SERVICE_NAME):
        return 1
    try:
        service_unit.remove_unit(unit_path)
    except (OSError, RuntimeError) as error:
        print(f'Could not uninstall service: {error}')
        return 1
    result = _run_systemctl('daemon-reload')
    if result == 0:
        print(f'Stopped, disabled, and removed {unit_path}')
    return result


def run(action: str, force: bool = False, notifications_enabled: bool = True) -> int:
    if action == 'install':
        return install(force, notifications_enabled)
    if action == 'uninstall':
        return uninstall()
    if action == 'logs':
        command = ['journalctl', '--user', '-u', SERVICE_NAME, '-f']
    elif action in SYSTEMCTL_ACTIONS:
        return _run_systemctl(action, SERVICE_NAME)
    else:
        raise ValueError(f'unsupported service action {action!r}')

    return subprocess.run(command, check=False).returncode
