import os
import shutil
import sys
import tempfile
from collections.abc import Mapping
from pathlib import Path

GENERATED_MARKER = '# Generated by macropad service install. DO NOT EDIT.'
SERVICE_NAME = 'macropad.service'
ACTION_PATH = '%h/bin:%h/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin'


class UnitOwnershipError(RuntimeError):
    pass


def validate_systemd_value(value: str) -> None:
    if any(ord(character) < 32 or ord(character) == 127 for character in value):
        raise ValueError('systemd values cannot contain control characters')


def quote_exec_path(path: Path) -> str:
    value = str(path)
    validate_systemd_value(value)
    escaped = value.replace('\\', '\\\\').replace('%', '%%').replace('"', '\\"')
    escaped = escaped.replace('$', '$$')
    return f'"{escaped}"'


def render_unit(executable: Path) -> str:
    if not executable.is_absolute():
        raise ValueError('service executable path must be absolute')
    return (
        f'{GENERATED_MARKER}\n'
        '[Unit]\n'
        'Description=Macropad Keyboard Interceptor\n'
        'After=default.target\n'
        '\n'
        '[Service]\n'
        'Type=simple\n'
        'Environment=PYTHONUNBUFFERED=1\n'
        f'Environment=PATH={ACTION_PATH}\n'
        f'ExecStart={quote_exec_path(executable)} --verbose listen --watch\n'
        'KillMode=mixed\n'
        'TimeoutStopSec=10\n'
        'Restart=on-failure\n'
        'RestartSec=5\n'
        '\n'
        '[Install]\n'
        'WantedBy=default.target\n'
    )


def resolve_executable(
    python_executable: str | None = None,
    path: str | None = None,
) -> Path:
    python_executable = python_executable or sys.executable
    adjacent = Path(python_executable).with_name('macropad')
    if adjacent.is_file() and os.access(adjacent, os.X_OK):
        return adjacent.absolute()

    command = shutil.which('macropad', path=path)
    if command:
        return Path(command).absolute()
    raise RuntimeError('could not locate the installed macropad executable')


def resolve_unit_path(
    environ: Mapping[str, str] | None = None,
    home: Path | None = None,
) -> Path:
    environ = os.environ if environ is None else environ
    home = Path.home() if home is None else home
    xdg_config_home = environ.get('XDG_CONFIG_HOME')
    if xdg_config_home and Path(xdg_config_home).is_absolute():
        config_home = Path(xdg_config_home)
    else:
        config_home = home / '.config'
    return config_home / 'systemd' / 'user' / SERVICE_NAME


def is_generated_unit(content: str) -> bool:
    return content.startswith(f'{GENERATED_MARKER}\n')


def validate_unit_ownership(path: Path, force: bool = False) -> None:
    if force:
        return
    try:
        content = path.read_text(encoding='utf-8')
    except FileNotFoundError:
        return
    if not is_generated_unit(content):
        raise UnitOwnershipError(
            f'{path} was not generated by Macropad; rerun with --force to replace it'
        )


def install_unit(path: Path, content: str, force: bool = False) -> None:
    validate_unit_ownership(path, force)

    path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    temporary_path = None
    try:
        with tempfile.NamedTemporaryFile(
            mode='w',
            encoding='utf-8',
            dir=path.parent,
            prefix=f'.{path.name}.',
            suffix='.tmp',
            delete=False,
        ) as temporary_file:
            temporary_path = Path(temporary_file.name)
            temporary_file.write(content)
            temporary_file.flush()
            os.fsync(temporary_file.fileno())
        temporary_path.chmod(0o644)
        os.replace(temporary_path, path)
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)


def remove_unit(path: Path) -> bool:
    try:
        content = path.read_text(encoding='utf-8')
    except FileNotFoundError:
        return False
    if not is_generated_unit(content):
        raise UnitOwnershipError(f'{path} was not generated by Macropad; refusing to remove it')
    path.unlink()
    return True
